### ISSUE TITLE
配置文件配置的线程池和Spring容器中用代码生成的线程池名字一样时覆盖的疑问

### ISSUE THREAD

**Issue by yueming158** [lyh200/dynamic-tp#14]
看代码发现如果配置文件配置的线程池和Spring容器中用代码配置的线程池名字一样时，注册的线程池对象会被设置成由配置文件生成的线程池对象（配置文件创建的对象并没有被容器管理），这样的话Spring容器中的创建的线程池对象其实没有被监控也无法动态配置，这样设计的原因是什么？谢谢！

**Comment by Redick01** [comment]
> 

你的问题是通过@Bean方式创建线程池并且通过@Autowired方式使用并不会被监控和动态配置吧？如果这样的话可以参考下正确的使用方式：

public static void main(String[] args) {
   DtpExecutor dtpExecutor = DtpRegistry.getExecutor("dynamic-tp-test-1");
   dtpExecutor.execute(() -> System.out.println("test"));
}

@Bean方式创建的线程池会被配置文件覆盖

**Comment by lyh200** [comment]
目前是这样的，框架自己定义了个容器存储通过配置文件创建的Executor对象，没有注册到spring容器中，需要通过DtpRegistry.getExecutor("dynamic-tp-test-1")这样获取，当然也可以注册到spring中，通过依赖注入使用，后续可以考虑加上

**Comment by yueming158** [comment]
> 目前是这样的，框架自己定义了个容器存储通过配置文件创建的Executor对象，没有注册到spring容器中，需要通过DtpRegistry.getExecutor("dynamic-tp-test-1")这样获取，当然也可以注册到spring中，通过依赖注入使用，后续可以考虑加上

好的，谢谢解答

**Comment by lyh200** [comment]
> 

已支持依赖注入方式使用

**Comment by lyh200** [comment]
> > 目前是这样的，框架自己定义了个容器存储通过配置文件创建的Executor对象，没有注册到spring容器中，需要通过DtpRegistry.getExecutor("dynamic-tp-test-1")这样获取，当然也可以注册到spring中，通过依赖注入使用，后续可以考虑加上
> 
> 好的，谢谢解答

已支持依赖注入方式使用
