### ISSUE TITLE
DtpWebRefreshListener为什么要判断applicationContext instanceof WebServerApplicationContext

### ISSUE THREAD

**Issue by Luckylau** [lyh200/dynamic-tp#17]
applicationContext初始化之后一定是AnnotationConfigServletWebServerApplicationContext，存放在ApplicationContextHolder中，必然是 instanceof WebServerApplicationContext的呀

**Comment by lyh200** [comment]
是的，现在确实可以不用做这个判断了，之前做web没分离加的判断
