### ISSUE TITLE
线程池对象创建的问题

### ISSUE THREAD

**Issue by mademeng** [lyh200/dynamic-tp#22]
能否实现，自动根据配置中心配置好的参数，项目启动时自动创建好线程池，并且可以使用@Resuce注入。配置好参数，无需添加任何构造代码，即可立即使用

**Comment by lyh200** [comment]
1.0.3之前的版本是采用了这种方式，最新代码里删除了这种方式，原因如下：

1.目前线程池对象完全交给spring管理了，而且实现了spring对象生命周期管理相关方法，以便在容器启动关闭时执行相应逻辑

2.手动注册到spring的Bean不能执行到生命周期相关方法，故建议最好是代码中先用@Bean简单创建一个，然后在配置中心配置参数

**Comment by mademeng** [comment]
使用spring拓展接口ImportBeanDefinitionRegistrar配合@Import注解实现。也是可以执行生命周期相关方法的吧。就是类似Mybatis集成spring的方式。
我自己也写了一个就我们公司内部使用的，使用方式和使用Mybatis类似，apollo配置好参数，自定义了一个注解@DpScan，指定namespace。@Resuce指定bean的名字，就可以直接使用了，无需写任何创建对象的代码，用起来很简单

**Comment by lyh200** [comment]
嗯，你说的这样确实是可以实现 ，但是我在想这样是不是使用起来倒还不如代码直接build这样方便直观呢；参数也不少，真正动态修改的就那几个核心参数，都放到配置中心需要对参数特别熟悉，还有像一些自定义的对象参数就没法直接放配置中心了（虽然可以反射生成，但是会有大量字符串字面量需要配置）；感觉不需要动态修改的参数代码配好，动态修改的放配置中心，配置项也会变少，比较清晰；这是我的看法；你想法挺好的，要不要这样做还值得商榷

**Comment by lyh200** [comment]
可以加个vx：yanhom1314，多多交流下经验

**Comment by mademeng** [comment]
我个人更倾向于，把线程池全部放到配置中心去管理，项目中使用到了哪些线程池，具体的配置参数有哪些，更清晰直观。
