### ISSUE TITLE
Monitor thread does not execute！

### ISSUE THREAD

**Issue by Redick01** [lyh200/dynamic-tp#6]
Because the implementation of different versions of Tomcat thread pool is different, an error is reported when the thread pool parameters cannot be obtained

If an error is reported in the thread pool scheduling method, the thread pool will not be scheduled

**Comment by lyh200** [comment]
Already fixed, that is a interesting issue, I will write a article to analyse it later.

**Comment by lyh200** [comment]
Already fixed, that is a interesting issue, I will write a article to analyse it later.
